language: swift
osx_image: xcode10

script:
  - set -eo pipefail && xcodebuild clean build -scheme YARCH -workspace YARCH.xcworkspace -destination 'platform=iOS Simulator,name=iPhone XS,OS=latest' | xcpretty
  - xcodebuild clean build -scheme TV -workspace YARCH.xcworkspace -destination 'platform=tvOS Simulator,name=Apple TV 4K,OS=latest' | xcpretty
  - gem install generamba
  - generamba template install
  - yes "Test Author" | generamba gen TestModule yarch --description 'Test Module' || true
  - xcodebuild clean test -scheme YARCH -workspace YARCH.xcworkspace -destination 'name=iPhone 7,OS=latest' -enableCodeCoverage YES | xcpretty
  - bundle exec danger
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'YARCH'
